const tariffsTypes = {
    ADD_TARIFF_LOADING: 'ADD_TARIFF_LOADING',
    ADD_TARIFF_SUCCESS: 'ADD_TARIFF_SUCCESS',

    VIEW_A_TARIFF_LOADING: 'VIEW_A_TARIFF_LOADING',
    VIEW_A_TARIFF_SUCCESS: 'VIEW_A_TARIFF_SUCCESS',

    VIEW_TARIFFS_LOADING: 'VIEW_TARIFFS_LOADING',
    VIEW_TARIFFS_SUCCESS: 'VIEW_TARIFFS_SUCCESS',

    EDIT_TARIFF_LOADING: 'EDIT_TARIFF_LOADING',
    EDIT_TARIFF_SUCCESS: 'EDIT_TARIFF_SUCCESS',

    DELETE_TARIFF_LOADING: 'DELETE_TARIFF_LOADING',
    DELETE_TARIFF_SUCCESS: 'DELETE_TARIFF_SUCCESS',
}

export default tariffsTypes;