
const authTypes = {
    LOGIN_USER_LOADING: 'LOGIN_USER_LOADING',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    GET_ROLES_LOADING: 'GET_ROLES_LOADING',
    GET_ROLES_SUCCESS: 'GET_ROLES_SUCCESS',
    ADD_USERS_LOADING: 'ADD_USERS_LOADING',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    LOGOUT_USER: 'LOGOUT_USER'
}

export default authTypes;