
const authTypes = {
    LOGIN_USER_LOADING: 'LOGIN_USER_LOADING',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    GET_ROLES_LOADING: 'GET_ROLES_LOADING',
    GET_ROLES_SUCCESS: 'GET_ROLES_SUCCESS',
    GET_ALL_DEVICES_LOADING: 'GET_ALL_DEVICES_LOADING',
    GET_ALL_DEVICES_SUCCESS: 'GET_ALL_DEVICES_SUCCESS',
    GET_DEVICE_READINGS_LOADING: 'GET_DEVICE_READINGS_LOADING',
    GET_DEVICE_READINGS_SUCCESS: 'GET_DEVICE_READINGS_SUCCESS',
    ADD_USERS_LOADING: 'ADD_USERS_LOADING',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_BRANCH_LOADING: 'ADD_USER_BRANCH_LOADING',
    ADD_USER_BRANCH_SUCCESS: 'ADD_USER_BRANCH_SUCCESS',
    EDIT_USER_LOADING: 'EDIT_USER_LOADING',
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    LOGOUT_USER: 'LOGOUT_USER'
}

export default authTypes;