
const deviceTypes = {
    GET_DEVICE_LOADING: 'GET_DEVICE_LOADING',
    GET_DEVICE_SUCCESS: 'GET_DEVICE_SUCCESS',
    GET_DEVICE_OVERVIEW_LOADING: 'GET_DEVICE_OVERVIEW_LOADING',
    GET_DEVICE_OVERVIEW_SUCCESS: 'GET_DEVICE_OVERVIEW_SUCCESS',
    ADD_DEVICE_LOADING: 'ADD_DEVICE_LOADING',
    ADD_DEVICE_SUCCESS: 'ADD_DEVICE_SUCCESS',
    GET_DEVICE_TYPE_LOADING: 'GET_DEVICE_TYPE_LOADING',
    GET_DEVICE_TYPE_SUCCESS: 'GET_DEVICE_TYPE_SUCCESS',
    EDIT_DEVICE_LOADING: 'EDIT_DEVICE_LOADING',
    EDIT_DEVICE_SUCCESS: 'EDIT_DEVICE_SUCCESS',
    DEACTIVATE_DEVICE_LOADING: 'DEACTIVATE_DEVICE_LOADING',
    DEACTIVATE_DEVICE_SUCCESS: 'DEACTIVATE_DEVICE_SUCCESS',
}

export default deviceTypes;