
const deviceTypes = {
    GET_DEVICE_LOADING: 'GET_DEVICE_LOADING',
    GET_DEVICE_SUCCESS: 'GET_DEVICE_SUCCESS',
    ADD_DEVICE_LOADING: 'ADD_DEVICE_LOADING',
    ADD_DEVICE_SUCCESS: 'ADD_DEVICE_SUCCESS',
}

export default deviceTypes;