
const clientTypes = {
    GET_CLIENT_LOADING: 'GET_CLIENT_LOADING',
    GET_CLIENT_SUCCESS: 'GET_CLIENT_SUCCESS',
    GET_CLIENT_OVERVIEW_LOADING: 'GET_CLIENT_OVERVIEW_LOADING',
    GET_CLIENT_OVERVIEW_SUCCESS: 'GET_CLIENT_OVERVIEW_SUCCESS',
    ADD_CLIENT_LOADING: 'ADD_CLIENT_LOADING',
    ADD_CLIENT_SUCCESS: 'ADD_CLIENT_SUCCESS',
    EDIT_CLIENT_LOADING: 'EDIT_CLIENT_LOADING',
    EDIT_CLIENT_SUCCESS: 'EDIT_CLIENT_SUCCESS',
}

export default clientTypes;