
const userTypes = {
    GET_USER_LOADING: 'GET_USER_LOADING',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_OVERVIEW_LOADING: 'GET_USER_OVERVIEW_LOADING',
    GET_USER_OVERVIEW_SUCCESS: 'GET_USER_OVERVIEW_SUCCESS',
    GET_CLIENT_USERS_LOADING: 'GET_CLIENT_USERS_LOADING',
    GET_CLIENT_USERS_SUCCESS: 'GET_CLIENT_USERS_SUCCESS',
    ADD_USER_LOADING: 'ADD_USER_LOADING',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_BRANCH_LOADING: 'ADD_USER_BRANCH_LOADING',
    ADD_USER_BRANCH_SUCCESS: 'ADD_USER_BRANCH_SUCCESS',
    EDIT_USER_LOADING: 'EDIT_USER_LOADING',
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    DEACTIVATE_USER_LOADING: 'DEACTIVATE_USER_LOADING',
    DEACTIVATE_USER_SUCCESS: 'DEACTIVATE_USER_SUCCESS',
    REMOVE_USER_LOADING: 'REMOVE_USER_LOADING',
    REMOVE_USER_SUCCESS: 'REMOVE_USER_SUCCESS',
}

export default userTypes;