
const userTypes = {
    GET_USER_LOADING: 'GET_USER_LOADING',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_OVERVIEW_LOADING: 'GET_USER_OVERVIEW_LOADING',
    GET_USER_OVERVIEW_SUCCESS: 'GET_USER_OVERVIEW_SUCCESS',
    ADD_USER_LOADING: 'ADD_USER_LOADING',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
}

export default userTypes;