
const branchTypes = {
    GET_BRANCH_LOADING: 'GET_BRANCH_LOADING',
    GET_BRANCH_SUCCESS: 'GET_BRANCH_SUCCESS',
    ADD_BRANCH_LOADING: 'ADD_BRANCH_LOADING',
    ADD_BRANCH_SUCCESS: 'ADD_BRANCH_SUCCESS',
}

export default branchTypes;