
const viewBranchesTypes = {
    GET_VIEWBRANCHES_LOADING: 'GET_VIEWBRANCHES_LOADING',
    GET_VIEWBRANCHES_SUCCESS: 'GET_VIEWBRANCHES_SUCCESS',
    GET_VIEWBRANCHES_TOP_LOADING: 'GET_VIEWBRANCHES_TOP_LOADING',
    GET_VIEWBRANCHES_TOP_SUCCESS: 'GET_VIEWBRANCHES_TOP_SUCCESS',
    ADD_VIEWBRANCHES_LOADING: 'ADD_VIEWBRANCHES_LOADING',
    ADD_VIEWBRANCHES_SUCCESS: 'ADD_VIEWBRANCHES_SUCCESS',
    GET_BRANCH_LOADING: 'GET_BRANCH_LOADING',
    GET_BRANCH_SUCCESS: 'GET_BRANCH_SUCCESS',
}

export default viewBranchesTypes;