
const viewBranchesTypes = {
    GET_VIEWBRANCHES_LOADING: 'GET_VIEWBRANCHES_LOADING',
    GET_VIEWBRANCHES_SUCCESS: 'GET_VIEWBRANCHES_SUCCESS',
    ADD_VIEWBRANCHES_LOADING: 'ADD_VIEWBRANCHES_LOADING',
    ADD_VIEWBRANCHES_SUCCESS: 'ADD_VIEWBRANCHES_SUCCESS',
}

export default viewBranchesTypes;